import os
import time
from config.settings import config

class ReportingModule:
    """Generate professional Markdown reports."""
    
    def __init__(self):
        self.report_dir = config.LOG_DIR
        if not os.path.exists(self.report_dir):
            os.makedirs(self.report_dir)

    def create_report(self, target, findings):
        filename = f"Stingbot_Report_{target}_{int(time.time())}.md"
        path = os.path.join(self.report_dir, filename)
        
        content = f"""# 🛡️ Security Assessment: {target}
**Generated by:** {config.BOT_NAME}
**Date:** {time.ctime()}

## Findings
{findings}

---
*Confidential - {config.USER_ALIAS}*
"""
        with open(path, "w") as f:
            f.write(content)
        return f"Report saved to {path}"
